name: Build & Deploy Demo App
on: [push]

env:
  DemoProject: 'src/OpenRpg.Demos.Web/OpenRpg.Demos.Web.csproj'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Web Demo
        run: dotnet publish -c Release -o demo "${{ env.DemoProject }}"
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3        
        with:
          path: demo/
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
